SELECT
    T2.REST_ID
    , T2.REST_NAME
    , T2.FOOD_TYPE
    , T2.FAVORITES
    , T2.ADDRESS
    , ROUND(AVG(T1.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW T1
INNER JOIN (
    SELECT
        REST_ID
        , REST_NAME
        , FOOD_TYPE
        , FAVORITES
        , ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) T2 
ON T1.REST_ID = T2.REST_ID
GROUP BY T2.REST_ID
ORDER BY SCORE DESC, T2.FAVORITES DESC;