SELECT
    T1.PRODUCT_ID
    , T1.PRODUCT_NAME
    , SUM(COALESCE(T1.PRICE, 0) * T2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT T1
INNER JOIN 
(SELECT
    PRODUCT_ID
    , AMOUNT
FROM FOOD_ORDER
WHERE SUBSTR(PRODUCE_DATE, 1, 7) = '2022-05') T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, T1.PRODUCT_ID;