    SELECT
        T3.MEMBER_NAME
        , T1.REVIEW_TEXT
        , DATE_FORMAT(T1.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
    FROM REST_REVIEW T1
    INNER JOIN (
        SELECT
            MEMBER_ID
            , RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) T2
    ON T1.MEMBER_ID = T2.MEMBER_ID
    AND T2.RNK = 1
    INNER JOIN MEMBER_PROFILE T3
    ON T1.MEMBER_ID = T3.MEMBER_ID
    ORDER BY T1.REVIEW_DATE, T1.REVIEW_TEXT;
    