SELECT
    ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM DEVELOPERS D
INNER JOIN SKILLCODES SK
ON SK.NAME IN ('Python', 'C#')
AND D.SKILL_CODE & SK.CODE > 0
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;