SELECT 
    SUM(HG.SCORE) AS SCORE
    , HE.EMP_NO
    , HE.EMP_NAME
    , HE.POSITION
    , HE.EMAIL
FROM HR_EMPLOYEES HE
INNER JOIN
    (SELECT
        EMP_NO
        , MAX(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO, HALF_YEAR) HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
ORDER BY SCORE DESC
LIMIT 1;
