SELECT
    CONCAT('/home/grep/src/', T1.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE T1
INNER JOIN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1) T2
ON T1.BOARD_ID = T2.BOARD_ID
ORDER BY T1.FILE_ID DESC;